### ISSUE TITLE
fails to build with gpgme >= 2.0.0

### ISSUE THREAD

**Issue by andreasstieger** [ueno/ruby-gpgme#202]
Starting with gpgme 2.0.0:

````
[   10s] gpgme_n.c:1648:9: error: implicit declaration of function ‘gpgme_op_trustlist_start’; did you mean ‘rb_s_gpgme_op_trustlist_start’? [-Wimplicit-function-declaration]
[   10s]  1648 |   err = gpgme_op_trustlist_start (ctx, StringValueCStr(vpattern),
[   10s]       |         ^~~~~~~~~~~~~~~~~~~~~~~~
[   10s]       |         rb_s_gpgme_op_trustlist_start
[   10s] gpgme_n.c: In function ‘rb_s_gpgme_op_trustlist_next’:
[   10s] gpgme_n.c:1657:3: error: unknown type name ‘gpgme_trust_item_t’
[   10s]  1657 |   gpgme_trust_item_t item;
[   10s]       |   ^~~~~~~~~~~~~~~~~~
[   10s] gpgme_n.c:101:32: warning: ‘rb_data_object_get_warning’ is deprecated: by TypedData [-Wdeprecated-declarations]
[   10s]   101 |   Data_Get_Struct(vctx, struct gpgme_context, ctx)
[   10s]       |                                ^~~~~~~~~~~~~
[...]
[   10s] gpgme_n.c:1667:9: error: implicit declaration of function ‘gpgme_op_trustlist_next’; did you mean ‘rb_s_gpgme_op_trustlist_next’? [-Wimplicit-function-declaration]
[   10s]  1667 |   err = gpgme_op_trustlist_next (ctx, &item);
[   10s]       |         ^~~~~~~~~~~~~~~~~~~~~~~
[   10s]       |         rb_s_gpgme_op_trustlist_next
[...]
[   10s] gpgme_n.c:110:35: error: ‘gpgme_trust_item_unref’ undeclared (first use in this function); did you mean ‘gpgme_result_unref’?
[   10s]   110 |   Data_Wrap_Struct(cTrustItem, 0, gpgme_trust_item_unref, item)
[   10s]       |                                   ^~~~~~~~~~~~~~~~~~~~~~
[...]
[   10s] /usr/include/ruby-3.4.0/ruby/internal/core/rdata.h:201:9: error: passing argument 2 of ‘rb_data_object_wrap_warning’ makes pointer from integer without a cast [-Wint-conversion]
[   10s]   201 |         (sval),                                   \
[   10s]       |         ^~~~~~
[   10s]       |         |
[   10s]       |         int
[...]
[   10s] gpgme_n.c:1671:52: error: invalid type argument of ‘->’ (have ‘int’)
[   10s]  1671 |       rb_iv_set (vitem, "@keyid", rb_str_new2 (item->keyid));
[   10s]       |                                                    ^~
````

Upstream information: https://dev.gnupg.org/T7262
Distribution bug: https://bugzilla.opensuse.org/show_bug.cgi?id=1246684
